# Markdownlint configuration file
default: true,
line-length: false
no-multiple-blanks: 0
blanks-around-headers: false
blanks-around-lists: false
header-increment: false
no-duplicate-header:
    siblings_only: true
first-header-h1: false # website only - the header usually adds the h1 element
first-line-h1: false
no-trailing-punctuation: false
single-title: false
no-inline-html: false
