# based on https://github.com/gitpod-io/template-docker-compose

tasks:
  - init: |
      docker-compose pull
  - command: |
      chmod a+x /workspace/nf-co.re && docker-compose up

ports:
  - port: 8888
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker