---
ports:
  - port: 4321
    onOpen: open-preview
  - port: 3306
    onOpen: ignore

vscode:
  extensions:
    - editorconfig.editorconfig
    - esbenp.prettier-vscode
tasks:
  # NOTE adding multiple tasks causes them to all run
  - name: Dev Server main-site
    init: npm install && npm run extract-cache

