# based on https://github.com/gitpod-io/template-docker-compose

tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up

vscode:
  extensions:
    - ms-azuretools.vscode-docker