# based on https://github.com/gitpod-io/template-docker-compose

tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up
ports:
  - port: 3306
    onOpen: ignore
  - port: 8888
    onOpen: open-preview
  # - port: 9200
  #   onOpen: open-preview
  # - port: 9300
  #   onOpen: ignore
  # - port: 9600
  #   onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker