# based on https://github.com/gitpod-io/template-docker-compose

tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker