version: "3.8"
services:
  web:
    container_name: nf-core-web
    image: webdevops/php-apache:7.4
    restart: always
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/public_html
    volumes:
      - .:/var/www/
    ports:
      - "8080:80"
    depends_on: 
      - composer
  composer:
    image: composer:2.1
    command: ["composer", "install"]
    volumes:
      - .:/var/www/
    working_dir: /var/www/
  npm:
    image: node:16-alpine3.12
    container_name: npm
    volumes:
      - .:/var/www/
    command: sh -c "npm install --quiet &&
                    npm run copy-assets &&
                    npm run watch-sass"
    working_dir: /var/www/
