blank_issues_enabled: false
contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here.
  - name: nf-core Slack #website channel
    url: https://nfcore.slack.com/channels/website
    about: Please ask and answer questions here.
