[functions]
external_node_modules = ["vscode-oniguruma","shiki"]
node_bundler = "esbuild"
[build]
command = "npm run build -w sites/pipeline-results"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF sites/main-site/src/components sites/pipeline-results public/pipelines.json" # don't build if there are no changes
[[headers]]
for = "/_astro/*"
[headers.values]
Access-Control-Allow-Origin = "https://nf-core-main-site.netlify.app"
