[functions]
external_node_modules = ["vscode-oniguruma","shiki"]
node_bundler = "esbuild"
[build]
environment = { NODE_VERSION = "20.4.0" }
command = "npm run build -w sites/pipeline-results"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF sites/pipeline-results public/pipelines.json" # don't build if there are no changes
