# yaml-language-server: $schema=yaml-schema.json
# nf-core contributors. Add yourself below to be featured on the website
# ----------------------------------------------------------------------
# Note that image_fn should correspond to logos in:
#    /public/images/contributors/white
#    /public/images/contributors/colour
# Please use svg images if possible.

local_sites:
  - full_name: IBU, Bern.
    url: 'https://www.bioinformatics.unibe.ch/'
    location: [46.952096, 7.428005]
  - full_name: UKRI Hartree centre, Daresbury
    url: 'https://maps.app.goo.gl/pEB5CDxgPbg7GLXb7'
    location: [53.3433353, -2.6384581]
  - full_name: Cosyne Therapeutics, London.
    url: 'https://maps.app.goo.gl/G327eD8PEQefbHcs8'
    location: [51.51565268907713, -0.13365964707324154]
  - full_name: Quadram Institute Bioscience, Norwich
    url: 'https://maps.app.goo.gl/xkDwoMQhnvPVGWVL7'
    location: [51.51565268907713, -0.13365964707324154]
  - full_name: Wellcome Genome Campus, Cambridge.
    url: 'https://www.wellcomegenomecampus.org'
    location: [52.6209296, 1.2158586]
  - full_name: ZS Associates, Buenos Aires
    url: 'https://www.zs.com/careers/where-we-work/latin-america/buenos-aires'
    location: [52.079047, 0.187607]
  - full_name: CRG, Barcelona.
    url: 'https://www.crg.eu/'
    location: [-34.546641062117786, -58.45772717852704]
  - full_name: Seqera offices in Barcelona
    url: 'https://seqera.io/'
    location: [41.40314671220324, 2.200052626497271]
  - full_name: Ghent University, Belgium.
    url: 'https://www.ugent.be/en'
    location: [51.01287821684896, 3.708004390525348]
  - full_name: Instituto do Cérebro, UFRN, Natal - Brazil
    url: 'https://neuro.ufrn.br/'
    location: [-5.833473893839016, -35.20483247479188]
  - full_name: Université de Sherbrooke, QC, Canada.
    url: 'https://scil.usherbrooke.ca/'
    location: [45.3797289, -71.9276139]
  - full_name: ZS Associates office, in (North of) Copenhagen.
    url: 'https://www.zs.com/careers/where-we-work/europe/copenhagen'
    location: [55.780384, 12.488322]
  - full_name: Institute Genetics & Development of Rennes.
    url: 'https://igdr.univ-rennes1.fr/'
    location: [48.117546, -1.696719]
  - full_name: GHGA, Heidelberg.
    url: 'https://www.ghga.de/events'
    location: [49.39643881353221, 8.673259933781846]
  - full_name: MPI-EVA, Leipzig.
    url: 'https://www.eva.mpg.de/index/'
    location: [51.3210835, 12.3954451]
  - full_name: RKI, Berlin.
    url: 'https://www.rki.de'
    location: [52.53913, 13.34729]
  - full_name: University of Tübingen.
    url: 'https://uni-tuebingen.de/einrichtungen/personalvertretungen-beratung-beauftragte/lageplaene/karte-a-morgenstelle/auf-der-morgenstelle-6'
    location: [48.53757295717644, 9.035516078124646]
  - full_name: DBB University of Pavia, Pavia.
    url: 'https://dbb.dip.unipv.it/it'
    location: [45.20249873618614, 9.138235385755026]
  - full_name: Ardigen office, in Kraków.
    url: 'https://ardigen.com/'
    location: [50.02159965915289, 19.89199888650787]
  - full_name: SciLifeLab, Stockholm.
    url: 'https://scilifelab.se/'
    location: [59.3505174, 18.0221508]
  - full_name: Superfluid office in South San Francisco
    url: 'https://maps.app.goo.gl/S2bbwxMkF12Tgm4U7'
    location: [37.6545572, -122.3973615]
  - full_name: University of Texas at Dallas
    url: 'https://map.concept3d.com/?id=1772#!m/434445'
    location: [32.991185005884084, -96.75017317150136]
  - full_name: University of Washington
    url: 'https://www.washington.edu/maps/#!/hsrr'
    location: [47.649292, -122.308287]
