name: FeedBot
on:
  schedule:
    # This will run every 10 minutes
    - cron: '*/10 * * * *'
jobs:
  rss-to-bluesky:
    runs-on: ubuntu-latest
    steps:
      - name: Generate cache key
        uses: actions/github-script@v6
        id: generate-key
        with:
          script: |
            core.setOutput('cache-key', new Date().valueOf())
      - name: Retrieve cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/blueskyfeedbot
          key: feed-cache-${{ steps.generate-key.outputs.cache-key }}
          restore-keys: feed-cache-
      - name: GitHub
        uses: 'joschi/blueskyfeedbot@v1'
        with:
          # This is the RSS feed you want to publish
          rss-feed: https://nf-co.re/blog/rss.xml
          # Template of status posted to Bluesky (Handlebars)
          template: '{{item.title}} {{item.link}} @nf-co.re #nextflow'
          # This is your service URL (optional)
          service-url: https://bsky.social
          # This is the Bluesky username (example: username.bsky.social)
          username: 'nf-co.re'
          # This is the app password you created earlier
          password: ${{ secrets.FEED_TO_BLUESKY }}
          # This is a path to the cache file, using the above cache path
          cache-file: ${{ github.workspace }}/blueskyfeedbot/cache.json
