name: Check Markdown links

on:
  push:
    paths:
    - '**.md'
  pull_request:
    paths:
    - '**.md'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - uses: gaurav-nelson/github-action-markdown-link-check@0.5.0
      with:
        use-quite-mode: 'yes'
        config-file: '../mlc_config.json'
