name: Check Markdown links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        fetch-depth: 1
    - uses: gaurav-nelson/github-action-markdown-link-check@0.4.0
