name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-composer:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: commit dependencies changes
      env:
        GITHUB_AUTH_TOKEN: ${{ secrets.nf_co_re_bot_auth_token }}
      run: |
        git config --global user.email "core@nf-co.re"
        git config --global user.name "nf-co.re-bot"
        git commit -am "add composer dependencies"
    - name: push dependencies changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.nf_co_re_bot_auth_token }}
