name: run npm 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-npm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install NPM dependencies
      run: npm install
    - name: copy assets
      run: npm run copy-assets
    - name: compile css
      run: npm run build-css
    - name: commit dependencies changes
      env:
        GITHUB_AUTH_TOKEN: ${{ secrets.nf_co_re_bot_auth_token }}
      run: |
        git config --global user.email "core@nf-co.re"
        git config --global user.name "nf-co.re-bot"
        git commit -am "add npm dependencies"
    - name: push dependencies changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.nf_co_re_bot_auth_token }}
