name: run npm 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-npm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install NPM dependencies
      run: npm install
    - name: copy assets
      run: npm run copy-assets
    - name: compile css
      run: npm run css-build