name: Generate images for docs
on:
  workflow_dispatch:
jobs:
  rich_codex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1

      - name: Install nf-core/tools
        run: pip install nf-core

      - name: Generate terminal images with rich-codex
        uses: ewels/rich-codex@v1
        env:
          COLUMNS: 100
          NFCORE_LINT_HIDE_PROGRESS: true
          NFCORE_MODULES_LINT_HIDE_PROGRESS: true
        with:
          commit_changes: 'true'
          terminal_width: 100
