name: Lint YAML
on:
  push:
    paths: '**.ya?ml'
  pull_request:
    paths: '**.ya?ml'

jobs:
  test_yaml:
    name: Test YAML syntax
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '10'

      - name: Install yaml-lint
        run: npm install -g yaml-lint

      - name: Run yaml-lint
        run: yamllint $(find ${GITHUB_WORKSPACE} -type f -name "*.yaml" -or -name "*.yml")
